Repository IT-Academy-Social-Projects-KRV/CMIYC, pull requests merged in 2022-05, with the labels that each got.

#213 Move urls and ports to environment variables
  Backend/external-apis/rest-server/pom.xml
  Backend/external-apis/rest-server/src/main/java/com/external/rest/Server.java
  Backend/external-apis/soap-server/pom.xml
  Backend/external-apis/soap-server/src/main/java/com/external/endpoint/SoapEndpoint.java
  Backend/external-apis/websocket-server/pom.xml
  Backend/external-apis/websocket-server/src/main/java/com/external/websocketserver/WebsocketEndpoint.java
  Backend/microservices/authority/src/main/resources/application.yml
  Backend/microservices/connector/src/main/resources/application.yml
  Backend/microservices/data/src/main/resources/application.yml
  Backend/microservices/search/src/main/java/com/ms/search/connectInterface/ConnectorConnect.java
  Backend/microservices/search/src/main/java/com/ms/search/connectInterface/DataConnect.java
  Backend/microservices/search/src/main/resources/application.yml
  Frontend/src/app/shared/http.client.service.ts
  Frontend/src/environments/environment.ts
Labels: devOps

#249 fixed error with CorsFilter
  Frontend/src/environments/environment.ts
Labels: error

#248 Feature 212 edit pom files in each microservice to mmake it standalone malyarskyy
  Backend/external-apis/mock-repository/pom.xml
  Backend/external-apis/rest-server/pom.xml
  Backend/external-apis/soap-server/pom.xml
  Backend/external-apis/websocket-server/pom.xml
  Backend/microservices/authority/pom.xml
  Backend/microservices/connector/pom.xml
  Backend/microservices/data/pom.xml
  Backend/microservices/eureka/pom.xml
  Backend/microservices/pom.xml
  Backend/microservices/search/pom.xml
Labels: devOps

#254 Feature #181 add scroll for user list
  Frontend/src/app/search-response/search-response.component.css
  Frontend/src/app/search-response/search-response.component.html
Labels: UI

#257 Feature 230 dockerize external APIs malyarskyy
  K8s/mock-repository.Dockerfile
  K8s/rest-server.Dockerfile
  K8s/soap-server.Dockerfile
  K8s/websocket-server.Dockerfile
Labels: devOps

#261 Added endpoints for schema admin
  Backend/microservices/data/src/main/java/com/ms/data/config/JWTSecurityConfigData.java
  Backend/microservices/data/src/main/java/com/ms/data/config/ObjectMapperConfig.java
  Backend/microservices/data/src/main/java/com/ms/data/controller/DataController.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/SchemaFile.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Combination.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Component.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Field.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Fields.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/InterfaceSchema.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Requirements.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Transaction.java
  Backend/microservices/data/src/main/java/com/ms/data/exception/BadXmlSchemaException.java
  Backend/microservices/data/src/main/java/com/ms/data/model/XmlObject.java
  Backend/microservices/data/src/main/java/com/ms/data/resource/XmlResource.java
  Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java
  Backend/microservices/data/src/main/java/com/ms/data/service/XmlReaderService.java
  Backend/microservices/data/src/main/java/com/ms/data/utils/XMLReaderWithoutNamespace.java
  Backend/microservices/search/src/main/java/com/ms/search/connectInterface/DataConnect.java
  Backend/microservices/search/src/main/java/com/ms/search/model/XmlObject.java
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/dataConnectTests/DataConnectUnitTests.java
Labels: microservice

#262 Feature 89 custom starter dima
  Backend/custom-starter/.gitignore
  Backend/custom-starter/.mvn/wrapper/maven-wrapper.jar
  Backend/custom-starter/.mvn/wrapper/maven-wrapper.properties
  Backend/custom-starter/README.MD
  Backend/custom-starter/mvnw
  Backend/custom-starter/mvnw.cmd
  Backend/custom-starter/pom.xml
  Backend/custom-starter/src/main/java/com.customstarter/config/CorsFilter.java
  Backend/custom-starter/src/main/java/com.customstarter/service/ServiceAutoConfiguration.java
  Backend/custom-starter/src/main/resources/META-INF/spring.factories
  Backend/custom-starter/src/main/resources/application.properties
  Backend/microservices/authority/pom.xml
  Backend/microservices/authority/src/main/java/com/ms/authority/config/CorsFilter.java
  Backend/microservices/data/pom.xml
  Backend/microservices/data/src/main/java/com/ms/data/config/CorsFilter.java
  Backend/microservices/search/pom.xml
Labels: microservice

#265 Feature 264 add runtime enviromens for angular malyarskyy
  Frontend/src/app/app.module.ts
  Frontend/src/app/shared/env.service.ts
  Frontend/src/app/shared/http.client.service.ts
  Frontend/src/assets/env.json
  Frontend/src/assets/set-env.sh
  Frontend/src/environments/env-model.ts
  Frontend/src/environments/environment.ts
  Frontend/tsconfig.json
Labels: UI

#270 add docker files for microservices
  K8s/connector.Dockerfile
  K8s/data.Dockerfile
  K8s/search.Dockerfile
Labels: devOps

#263 Load schema list from data API, add schema content viewer, add delete button
  Frontend/src/app/admin-create-schema-form/admin-create-schema-form.component.ts
  Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.html
  Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.ts
  Frontend/src/app/admin-user-is-active-toggle/admin-user-is-active-toggle-component-spec.ts
  Frontend/src/app/admin-user-is-active-toggle/admin-user-is-active-toggle-component.css
  Frontend/src/app/admin-user-is-active-toggle/admin-user-is-active-toggle-component.html
  Frontend/src/app/admin-user-is-active-toggle/admin-user-is-active-toggle-component.ts
  Frontend/src/app/admin-view-schema/admin-view-schema-component-spec.ts
  Frontend/src/app/admin-view-schema/admin-view-schema-component.css
  Frontend/src/app/admin-view-schema/admin-view-schema-component.html
  Frontend/src/app/admin-view-schema/admin-view-schema-component.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/shared/data/schema.ts
  Frontend/src/app/shared/http.client.service.ts
  Frontend/src/app/user-search-interface/user-search-interface.component.ts
Labels: UI

#256 fix links highlighting
  Frontend/src/app/search-response/search-response.component.html
Labels: UI

#258 paginaton added
  Frontend/package.json
  Frontend/src/app/app.module.ts
  Frontend/src/app/search-response/search-response.component.html
  Frontend/src/app/search-response/search-response.component.ts
  Frontend/src/app/shared/Mock/Repo.ts
  Frontend/src/app/shared/Mock/Response.ts
Labels: UI

#267 Added select schema endpoint
  Backend/microservices/data/src/main/java/com/ms/data/config/JWTSecurityConfigData.java
  Backend/microservices/data/src/main/java/com/ms/data/controller/DataController.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/SchemaFile.java
  Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java
Labels: microservice

#268 Select and highlight schema from UI
  Frontend/src/app/admin-create-schema-form/admin-create-schema-form.component.ts
  Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.css
  Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.html
  Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/shared/data/schema.ts
  Frontend/src/app/shared/http.client.service.ts
Labels: UI

#266 Feature 183 partial search for admin user lera
  Backend/microservices/authority/src/main/java/com/ms/authority/controller/UserController.java
  Backend/microservices/authority/src/main/java/com/ms/authority/repository/UserRepository.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
Labels: auth+db

#271 frontend.Dockerfile added and set-env.sh fixed
  Frontend/src/assets/set-env.sh
  K8s/frontend.Dockerfile
  K8s/nginx.conf
Labels: UI, devOps

#275 added deleting schema opportunity
  Backend/microservices/data/src/main/java/com/ms/data/controller/DataController.java
  Backend/microservices/data/src/main/java/com/ms/data/controller/RestExceptionHandler.java
  Backend/microservices/data/src/main/java/com/ms/data/exception/CurrentSelectedSchemaException.java
  Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java
Labels: microservice

#272 Feature 179 pagination on admin page horishny
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/shared/http.client.service.ts
Labels: UI

#289 registration user refactor
  Backend/microservices/authority/src/main/java/com/ms/authority/controller/UserController.java
  Backend/microservices/authority/src/main/java/com/ms/authority/exception/RestExceptionHandler.java
  Backend/microservices/authority/src/main/java/com/ms/authority/repository/UserRepository.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
Labels: auth+db

#283 Edit user registration on UI
  Frontend/src/app/shared/http.client.service.ts
Labels: UI

#293 Move shared classes form search api and data api to starter
  Backend/custom-starter/pom.xml
  Backend/custom-starter/src/main/java/com/customstarter/config/CorsFilter.java
  Backend/custom-starter/src/main/java/com/customstarter/config/ServiceAutoConfiguration.java
  Backend/custom-starter/src/main/java/com/customstarter/model/Date.java
  Backend/custom-starter/src/main/java/com/customstarter/model/Name.java
  Backend/custom-starter/src/main/java/com/customstarter/model/RaceCode.java
  Backend/custom-starter/src/main/java/com/customstarter/model/SexCode.java
  Backend/custom-starter/src/main/java/com/customstarter/model/StateCode.java
  Backend/custom-starter/src/main/java/com/customstarter/model/request/SearchRequest.java
  Backend/custom-starter/src/main/java/com/customstarter/model/request/SearchRequestPayload.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/Schema.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/combination/ApiCombination.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/combination/CombinationFieldReference.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/ComplexInput.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/HtmlInput.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/HtmlInputType.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/NumberInput.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/Select.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/SelectOption.java
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/TextInput.java
  Backend/custom-starter/src/main/java/com/customstarter/utils/ApiError.java
  Backend/custom-starter/src/main/java/com/customstarter/utils/ImageIndicatorDeserializer.java
  Backend/custom-starter/src/main/resources/META-INF/spring.factories
  Backend/microservices/data/src/main/java/com/ms/data/controller/DataController.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/form/ApiCombination.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/form/input/HtmlInput.java
  Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java
  Backend/microservices/data/src/main/java/com/ms/data/service/SearchFormBuilderService.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/HtmlInputBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/complex/DateObjectInputBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/complex/NameObjectInputBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/primitive/AlphabeticHtmlInputBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/primitive/AlphanumericHtmlInputBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/primitive/NumericHtmlInputBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/ImageIndicatorSelectBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/RaceCodeSelectBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/SexCodeSelectBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/StateSelectBuilder.java
  Backend/microservices/search/src/main/java/com/ms/search/connectInterface/ConnectorConnect.java
  Backend/microservices/search/src/main/java/com/ms/search/connectInterface/DataConnect.java
  Backend/microservices/search/src/main/java/com/ms/search/controller/SearchController.java
  Backend/microservices/search/src/main/resources/application.yml
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/connectorConnectTests/ConnectorConnectUnitTests.java
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/searchControllerTests/SearchControllerIntegrationTests.java
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/searchControllerTests/SearchControllerUnitTests.java
Labels: microservice

#286 Feature 186 update and delete operations for users horishny
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.css
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.html
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.spec.ts
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/shared/http.client.service.ts
Labels: UI

#295 Feature 117 deployment igor
  .gitignore
  Backend/microservices/authority/src/main/resources/application.yml
  Frontend/src/environments/environment.prod.ts
  K8s/DB/deployment.yml
  K8s/DB/service.yml
  K8s/DB/volume-claim.yml
  K8s/DB/volume.yml
  K8s/authority.Dockerfile
  K8s/backendconfig.yml
  K8s/deployment.yml
  K8s/ingress.yml
  K8s/service.yml
  cloudbuild.yml
Labels: devOps

#294 Feature 237 refactor mock repository dima
  Backend/external-apis/README.md
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/API.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/Date.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/Gender.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/Name.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/PersonData.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/RaceCode.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchRequest.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchResponse.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/Payload.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/PayloadOne.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/PayloadThree.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/PayloadTwo.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/RequestPayloadOne.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/RequestPayloadThree.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/RequestPayloadTwo.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/Response.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/ResponseOne.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/ResponseThree.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/ResponseTwo.java
  Backend/external-apis/mock-repository/src/main/java/com/external/entity/Person.java
  Backend/external-apis/mock-repository/src/main/java/com/external/repository/PersonRepository.java
  Backend/external-apis/mock-repository/src/main/java/com/external/server/Server.java
  Backend/external-apis/mock-repository/src/main/resources/mock_data.json
Labels: microservice

#287 Fix #231 pagination for user search
  Backend/microservices/authority/src/main/java/com/ms/authority/controller/UserController.java
  Backend/microservices/authority/src/main/java/com/ms/authority/repository/UserRepository.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/EmailService.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
Labels: auth+db

#297 Refactored connector API. Rest and websocket connections now returns data. SOAP still broken.
  Backend/custom-starter/src/main/java/com/customstarter/model/Date.java
  Backend/custom-starter/src/main/java/com/customstarter/model/Name.java
  Backend/custom-starter/src/main/java/com/customstarter/model/request/SearchRequestPayload.java
  Backend/custom-starter/src/main/java/com/customstarter/model/response/Response.java
  Backend/custom-starter/src/main/java/com/customstarter/model/response/ResponseOne.java
  Backend/custom-starter/src/main/java/com/customstarter/model/response/ResponseThree.java
  Backend/custom-starter/src/main/java/com/customstarter/model/response/ResponseTwo.java
  Backend/external-apis/mock-repository/pom.xml
  Backend/external-apis/mock-repository/src/main/java/com/external/MockRepositoryApplication.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/API.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/Date.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/Name.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/RaceCode.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchResponse.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/Payload.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/PayloadOne.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/PayloadThree.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/request/PayloadTwo.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/ResponseOne.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/ResponseThree.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/response/ResponseTwo.java
  Backend/external-apis/mock-repository/src/main/java/com/external/entity/Person.java
  Backend/external-apis/mock-repository/src/main/java/com/external/repository/PersonRepository.java
  Backend/external-apis/mock-repository/src/main/java/com/external/server/Server.java
  Backend/microservices/connector/pom.xml
  Backend/microservices/connector/src/main/java/com/ms/connector/config/ConnectionsConfig.java
  Backend/microservices/connector/src/main/java/com/ms/connector/controller/SearchQueryController.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/PersonData.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/SearchQuery.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/SearchResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/response/ApiResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/response/RestApiResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/response/SoapApiResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/response/WebsocketApiResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/exception/ApiErrorException.java
  Backend/microservices/connector/src/main/java/com/ms/connector/exception/UnknownApiNameException.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/ApiService.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/ApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/HttpApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/RestApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/SoapApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/WebsocketApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/converter/BodyConverter.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/converter/JsonBodyConverter.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/converter/SoapBodyConverter.java
  Backend/microservices/connector/src/main/resources/application.yml
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/ImageIndicatorSelectBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/SexCodeSelectBuilder.java
  Frontend/src/app/shared/data/json-form.ts
  K8s/connector.Dockerfile
  K8s/mock-repository.Dockerfile
Labels: microservice

#278 #198 Remove spring.mail.password from application.yml
  Backend/microservices/authority/README.MD
  Backend/microservices/authority/img.png
  Backend/microservices/authority/img_1.png
Labels: microservice

#292 feature_291_ChangePageSizeUserAdmin_horishny
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
Labels: UI

#302 Add thirty test users: 10 users, 10 admin users, 10 admin schema
  Backend/microservices/authority/README.MD
  Backend/microservices/authority/src/main/resources/db/migration/V7__AddThirtyTestUsers.sql
Labels: auth+db

#305 fix qrCode view in Gmail
  Backend/microservices/authority/src/main/java/com/ms/authority/service/EmailService.java
  Backend/microservices/authority/src/main/resources/template/emailConfirmation.html
Labels: auth+db, error

#316 Update README and rename APIs
  Backend/custom-starter/README.MD
  Backend/external-apis/README.md
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/API.java
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchRequest.java
  Backend/microservices/connector/README.MD
  Backend/microservices/connector/src/main/java/com/ms/connector/controller/SearchQueryController.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/ApiService.java
  Backend/microservices/connector/src/main/resources/application.yml
Labels: microservice

#311 Add CacheService class
  Backend/custom-starter/src/main/java/com/customstarter/model/response/SearchResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/controller/SearchQueryController.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/ApiService.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/ApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/RestApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/SoapApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/WebsocketApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/converter/SoapBodyConverter.java
  Backend/microservices/search/pom.xml
  Backend/microservices/search/src/main/java/com/ms/search/config/CaffeineConfig.java
  Backend/microservices/search/src/main/java/com/ms/search/controller/SearchController.java
  Backend/microservices/search/src/main/java/com/ms/search/service/CacheService.java
  Backend/microservices/search/src/main/java/com/ms/search/service/ConnectorConnect.java
  Backend/microservices/search/src/main/java/com/ms/search/service/DataConnect.java
  Backend/microservices/search/src/main/resources/application.yml
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/connectorConnectTests/ConnectorConnectUnitTests.java
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/searchControllerTests/SearchControllerIntegrationTests.java
  Backend/microservices/search/src/test/java/com/mkyong/core/controller/searchControllerTests/SearchControllerUnitTests.java
Labels: microservice

#314 add syncronized to register method
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
Labels: microservice

#313 refactor soap
  Backend/custom-starter/pom.xml
  Backend/custom-starter/src/main/java/com/customstarter/model/Date.java
  Backend/custom-starter/src/main/java/com/customstarter/model/Name.java
  Backend/custom-starter/src/main/java/com/customstarter/model/response/Response.java
  Backend/custom-starter/src/main/java/com/customstarter/model/response/ResponseTwo.java
  Backend/external-apis/soap-server/pom.xml
  Backend/external-apis/soap-server/src/main/java/com/external/config/SoapEndpointConfig.java
  Backend/external-apis/soap-server/src/main/java/com/external/endpoint/ResponseEndpoint.java
  Backend/external-apis/soap-server/src/main/java/com/external/utils/StringObjectMap.java
  Backend/external-apis/soap-server/src/main/java/com/external/utils/StringObjectMapAdapter.java
  Backend/external-apis/soap-server/src/main/resources/bindings.xjb
  Backend/external-apis/soap-server/src/main/resources/persons.xsd
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/response/SoapApiResponse.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/SoapApiConnection.java
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/converter/SoapBodyConverter.java
Labels: microservice

#309 fix admin users deleting
  Backend/microservices/authority/src/main/java/com/ms/authority/entity/Role.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
Labels: auth+db, error

#315 Added unit tests for mock repository
  Backend/external-apis/mock-repository/pom.xml
  Backend/external-apis/mock-repository/src/main/java/com/external/dto/SearchResponse.java
  Backend/external-apis/mock-repository/src/main/java/com/external/repository/PersonRepository.java
  Backend/external-apis/mock-repository/src/test/java/com/external/SearchRequestUnitTests.java
  Backend/external-apis/mock-repository/src/test/java/com/external/ServerUnitTests.java
  Backend/external-apis/mock-repository/src/test/java/com/external/helpers/MockedWebsocketClient.java
Labels: microservice

#308 add api checkboxes on search form
  Frontend/src/app/json-form/json-form-component.css
  Frontend/src/app/json-form/json-form-component.html
  Frontend/src/app/json-form/json-form-component.ts
Labels: UI

#319 Fix search form reset
  Frontend/src/app/json-form/json-form-component.ts
  Frontend/src/app/shared/form.data.service.ts
Labels: UI

#323 Added empty list as default value
  Backend/microservices/connector/src/main/java/com/ms/connector/dto/response/SoapApiResponse.java
Labels: microservice, error

#321 Remove access token form exceptions
  Backend/microservices/authority/src/main/java/com/ms/authority/config/granters/TfaTokenGranter.java
  Backend/microservices/authority/src/main/java/com/ms/authority/utils/Authorities.java
Labels: auth+db, error

#318 126 create accordion view for response from search api
  Backend/microservices/search/src/main/java/com/ms/search/service/CacheService.java
  Frontend/src/app/json-form/json-form-component-spec.ts
  Frontend/src/app/json-form/json-form-component.ts
  Frontend/src/app/search-response/search-response.component.css
  Frontend/src/app/search-response/search-response.component.html
  Frontend/src/app/search-response/search-response.component.ts
  Frontend/src/app/shared/Mock/Repo.ts
  Frontend/src/app/shared/Mock/Response.ts
  Frontend/src/app/shared/data/search.response.ts
  Frontend/src/app/shared/http.client.service.ts
  Frontend/src/assets/images/user.svg
Labels: UI

#320 Schema validation
  Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java
Labels: auth+db

#312 Feature 80 project logo horishny
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
  Frontend/src/app/header/header.component.html
  Frontend/src/app/login-form/login-form.component.css
  Frontend/src/app/login-form/login-form.component.html
  Frontend/src/app/login-form/login-form.component.ts
  Frontend/src/app/register/register.component.css
  Frontend/src/app/register/register.component.html
  Frontend/src/app/sidebar/sidebar.component.html
  Frontend/src/app/two-factor-authentication-form/two-factor-authentication-form.component.css
  Frontend/src/app/two-factor-authentication-form/two-factor-authentication-form.component.html
  Frontend/src/assets/images/back-ground-logo.svg
  Frontend/src/assets/images/h-logo-hq.svg
  Frontend/src/assets/images/sb-logo-hq-24.svg
  Frontend/src/favicon.ico
  Frontend/src/index.html
Labels: UI

#317 Feature 252 partial search
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
  Frontend/src/app/shared/http.client.service.ts
Labels: UI

#322 Added unit tests for XmlReaderService and SearchFormBuilderService
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Combination.java
  Backend/microservices/data/src/main/java/com/ms/data/dto/xml/Requirements.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/complex/ComplexObjectInputBuilder.java
  Backend/microservices/data/src/test/java/com/ms/data/xml/SearchFormBuilderServiceTests.java
  Backend/microservices/data/src/test/java/com/ms/data/xml/XmlReaderServiceTests.java
  Backend/microservices/data/src/test/resources/schema.xml
Labels: microservice

#324 244 add loading animation and disable
  Frontend/src/app/admin-create-schema-form/admin-create-schema-form.component.html
  Frontend/src/app/admin-manage-schema-list/admin-manage-schema-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-user-form/admin-user-form.component.html
  Frontend/src/app/admin-user-form/admin-user-form.component.ts
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.html
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.ts
  Frontend/src/app/app.module.ts
  Frontend/src/app/json-form/json-form-component.ts
  Frontend/src/app/search-response/search-response.component.html
  Frontend/src/app/search-response/search-response.component.ts
  Frontend/src/app/spinner/spinner.component.css
  Frontend/src/app/spinner/spinner.component.html
  Frontend/src/app/spinner/spinner.component.ts
  Frontend/src/app/user-search-interface/user-search-interface.component.html
  Frontend/src/app/user-search-interface/user-search-interface.component.ts
  Frontend/src/styles.css
Labels: UI

#326 Added validation on user add form and user update form
  Backend/microservices/authority/src/main/java/com/ms/authority/dto/RegistrationRequestData.java
  Backend/microservices/authority/src/main/java/com/ms/authority/exception/BadRegisterDataException.java
  Backend/microservices/authority/src/main/java/com/ms/authority/exception/NotEnoughRolesSelectedException.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
  Frontend/src/app/admin-user-form/admin-user-form.component.html
  Frontend/src/app/admin-user-form/admin-user-form.component.ts
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.html
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.ts
Labels: UI, error

#329 fix loading animation for search on admin page
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.html
  Frontend/src/app/admin-manage-user-list/admin-manage-user-list.component.ts
Labels: UI

#335 Feature recaptcha
  Backend/microservices/authority/pom.xml
  Backend/microservices/authority/src/main/java/com/ms/authority/controller/UserController.java
  Backend/microservices/authority/src/main/java/com/ms/authority/dto/ConfirmRegisterData.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/RecaptchaService.java
  Backend/microservices/authority/src/main/java/com/ms/authority/service/UserService.java
  Frontend/package.json
  Frontend/src/app/app.module.ts
  Frontend/src/app/register/register.component.html
  Frontend/src/app/register/register.component.ts
  Frontend/src/app/shared/http.client.service.ts
  K8s/deployment.yml
Labels: auth+db

#345 fixed invalid activation link message
  Backend/microservices/authority/src/main/java/com/ms/authority/exception/TokenNotFoundException.java
  Backend/microservices/authority/src/main/resources/application.yml
  Frontend/src/app/shared/http.client.service.ts
Labels: error

#346 Rename "Unknown" to "Select..." in selects
  Backend/custom-starter/src/main/java/com/customstarter/model/schema/input/SelectOption.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/RaceCodeSelectBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/SexCodeSelectBuilder.java
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/select/StateSelectBuilder.java
Labels: microservice, error

#337 disable create in admin user if invalid data
  Frontend/src/app/admin-user-form/admin-user-form.component.html
  Frontend/src/app/admin-user-update-form/admin-user-update-form.component.html
Labels: UI, error

#347 Now max year in birthdate input is current year and min year is 1900
  Backend/microservices/data/src/main/java/com/ms/data/service/builders/complex/DateObjectInputBuilder.java
Labels: microservice, error

#348 Format JSON in schema viewer
  Frontend/src/app/admin-view-schema/admin-view-schema-component.ts
Labels: UI

#349 Removed maxlength and minlength
  Frontend/src/app/admin-user-form/admin-user-form.component.html
Labels: UI, error

#344 Add "Hello" to registration message
  Backend/microservices/authority/src/main/resources/template/emailConfirmation.html
Labels: auth+db

#350 Fixed invalid schema message
  Backend/microservices/data/src/main/java/com/ms/data/exception/InvalidSchemaException.java
  Backend/microservices/data/src/main/java/com/ms/data/service/CloudStorageService.java
  Frontend/src/app/admin-create-schema-form/admin-create-schema-form.component.ts
Labels: UI, error

#352 Added tooltips for birthDate and name
  Frontend/src/app/json-form/json-form-component.html
Labels: UI

#353 Fixed error in soap converter
  Backend/microservices/connector/src/main/java/com/ms/connector/service/api/converter/SoapBodyConverter.java
  Frontend/src/app/search-response/search-response.component.html
Labels: microservice, error
